### ISSUE TITLE
use of deprecated method `chrono::DateTime::<Tz>::timestamp_nanos`

### ISSUE THREAD

**Issue by evenyag** [GreptimeTeam/greptimedb#2507] opened 2023-09-27 04:22 UTC
### What type of enhancement is this?

Other

### What does the enhancement do?

`common-time` crate has the following compiler warnings
```bash
   Compiling common-time v0.4.0-nightly (/Users/evenyag/codes/greptime/bench-mito2/src/common/time)
warning: use of deprecated method `chrono::DateTime::<Tz>::timestamp_nanos`: use `timestamp_nanos_opt()` instead
  --> /Users/evenyag/codes/greptime/bench-mito2/src/common/time/src/timestamp.rs:66:41
   |
66 |             TimeUnit::Nanosecond => now.timestamp_nanos(),
   |                                         ^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default

warning: use of deprecated method `chrono::TimeZone::datetime_from_str`: use `DateTime::parse_from_str` instead
   --> /Users/evenyag/codes/greptime/bench-mito2/src/common/time/src/timestamp.rs:301:29
    |
301 |         if let Ok(ts) = Utc.datetime_from_str(s, "%Y-%m-%d %H:%M:%S%.fZ") {
    |                             ^^^^^^^^^^^^^^^^^

```

### Implementation challenges

We need to fix unit tests.

**Comment by v0y4g3r** [comment] 2023-10-07 13:46
Closing this issue as I cannot reproduce on 657542c0b802dc31d8a064540f7e5b9ed185d5ae. 
Feel free to reopen it once anybody come across it again.

**Closed by v0y4g3r** 2023-10-07 13:46 UTC
Labels: enhancement
