### ISSUE TITLE
Compatible with the `bucket` parameter for influxdb line protocol

### ISSUE THREAD

**Issue by nicecui** [GreptimeTeam/greptimedb#3413] opened 2024-02-29 08:07 UTC
### What type of enhancement is this?

API improvement

### What does the enhancement do?

The influxdb line protocol v2 and v3 use the `bucket` parameter to indicate the database name, for example:

```
curl --request POST \
"https://url?org=YOUR_ORG&bucket=YOUR_BUCKET&precision=ns" \
```

GreptimeDB uses the `db` parameter to indicate the database name:

```
curl 'http://localhost:4000/v1/influxdb/api/v2/write?db=public'
```

When using the client libs of InfluxDB, users cannot change the `bucket` parameter to `db` parameter.
Does Greptime plan to support the `bucket` parameter to indicate the database?

**Comment by tisonkun** [comment] 2024-03-02 06:31
Related code - 

https://github.com/GreptimeTeam/greptimedb/blob/7d30c2484b826f269b6c3efe2b41929e0c91e6c1/src/servers/src/http/influxdb.rs#L41-L94

Should update the ref to `db` param with `bucket` and correspondingly update the tests or any other references.

**Comment by tisonkun** [comment] 2024-03-02 06:34
Related InfluxeDB docs -

* https://docs.influxdata.com/influxdb/v1/tools/api/#apiv2write-http-endpoint
* https://docs.influxdata.com/influxdb/cloud/api/#operation/PostWrite
* https://docs.influxdata.com/influxdb/cloud/api/v1-compatibility/#tag/Write

It seems that v1 use `db` but from v2 it uses `bucket`.

**Comment by etolbakov** [comment] 2024-03-02 07:26
@tisonkun if this is not a super urgent one (say, I have a week or two) I'd like giving it a shot

**Comment by tisonkun** [comment] 2024-03-02 07:44
@etolbakov Thanks! It should not be urgent. Feel free to send a patch and ping me as the reviewer :D

**Comment by etolbakov** [comment] 2024-03-02 13:46
@tisonkun 
I had a quick look at the influxdb docs you've provided and Greptime code and would like to confirm if I'm not missing anything:
There are 2 functions that support write to influxdb:
   - `influxdb_write_v1` that has a route `/write` and query parameter `db`
   - `influxdb_write_v2` that has a route `/api/v2/write` and query parameter `bucket`

I understand that the current implementation doesn't have any issues and matches the influxdb API.

@nicecui 
Could you please tell me where does the request `curl 'http://localhost:4000/v1/influxdb/api/v2/write?db=public' come from?
I have a feeling that this API endpoint is used in an incorrect way but works because "public" is the [default name schema name](https://github.com/GreptimeTeam/greptimedb/blob/7d30c2484b826f269b6c3efe2b41929e0c91e6c1/src/servers/src/http/influxdb.rs#L67-L69) and this API endpoint should be used with `?bucket=public`.

Out of curiosity I tried providing a different name for the schema, please find the results below:

<details>
  <summary>http://localhost:4000/v1/influxdb/api/v2/write?db=evttest</summary>
  ```sh
  at 13:35:38 ❯ curl -v --location --request POST 'http://localhost:4000/v1/influxdb/api/v2/write?db=evttest' \
   --header 'Content-Type: application/json' \
   --data-raw 'datum,host=host2 cpu=1.4 1664370459457010101'
  *   Trying 127.0.0.1:4000...
  * Connected to localhost (127.0.0.1) port 4000 (#0)
  > POST /v1/influxdb/api/v2/write?db=evttest HTTP/1.1
  > Host: localhost:4000
  > User-Agent: curl/8.0.1
  > Accept: */*
  > Content-Type: application/json
  > Content-Length: 44
  >
  < HTTP/1.1 500 Internal Server Error
  < content-type: application/json
  < content-length: 55
  < date: Sat, 02 Mar 2024 13:36:24 GMT
  <
  * Connection #0 to host localhost left intact
  {"error":"Failed to find schema, schema info: evttest"}%
  ```
</details>

<details>
  <summary>http://localhost:4000/v1/influxdb/api/v2/write?bucket=evttest</summary>
  ```sh
  curl -v --location --request POST 'http://localhost:4000/v1/influxdb/api/v2/write?bucket=evttest' \
  --header 'Content-Type: application/json' \
  --data-raw 'datum,host=host3 cpu=1.5 1664370459457010102'
  *   Trying 127.0.0.1:4000...
  * Connected to localhost (127.0.0.1) port 4000 (#0)
  > POST /v1/influxdb/api/v2/write?bucket=evttest HTTP/1.1
  > Host: localhost:4000
  > User-Agent: curl/8.0.1
  > Accept: */*
  > Content-Type: application/json
  > Content-Length: 44
  >
  < HTTP/1.1 204 No Content
  < date: Sat, 02 Mar 2024 13:35:38 GMT
  ```
</details>

Please let me know what do you think?

**Comment by tisonkun** [comment] 2024-03-02 14:03
@etolbakov Thanks a lot for your time to investigate this. I agree that the implementation seems correct.

@nicecui This seems some incorrect docs issue? I share the question -

> Could you please tell me where does the request curl 'http://localhost:4000/v1/influxdb/api/v2/write?db=public' come from?

---

> but works because "public" is the [default name schema name](https://github.com/GreptimeTeam/greptimedb/blob/7d30c2484b826f269b6c3efe2b41929e0c91e6c1/src/servers/src/http/influxdb.rs#L67-L69) and this API endpoint should be used with ?bucket=public.

@etolbakov have you checked if InfluxDB has this default schema name manner? Or it returns an error if bucket unspecified.

**Comment by etolbakov** [comment] 2024-03-02 14:19
Looks like for the `db` query parameter, influxdb will create a default bucket with 3-day retention policy if it's not provided.
https://docs.influxdata.com/influxdb/cloud/api/v1-compatibility/#tag/Write

As for the `bucket` query parameter it's not stated the same (so my understanding - it is not created):
https://docs.influxdata.com/influxdb/v2/api/#operation/PostWrite

**Comment by nicecui** [comment] 2024-03-04 02:52
@etolbakov Thank you for your interest in this issue!

We need the `/api/v2/write` API to support the `bucket` parameter.
The expected API behavior:

* If there is no parameter `db` or `bucket`, the default database `public` should be used.
* Use the value of the `db` parameter if exists.
* Use the value of the `bucket` parameter if there is no `db` perameter.
* If the database specified does not exist, throw error `Database not found`.

**Comment by nicecui** [comment] 2024-03-04 03:13
> I have a feeling that this API endpoint is used in an incorrect way but works because "public" is the [default name schema name](https://github.com/GreptimeTeam/greptimedb/blob/7d30c2484b826f269b6c3efe2b41929e0c91e6c1/src/servers/src/http/influxdb.rs#L67-L69) and this API endpoint should be used with ?bucket=public.

Here is a bug: If the database specified by the `db` parameter does not exist, the `public` database is used. 
The correct behavior is to throw an error. We think there is no users using this bug as a feature 😜, let's fix it now.

**Comment by etolbakov** [comment] 2024-03-04 09:09
Thanks for explaining the desired behaviour @nicecui.

> We need the `/api/v2/write` API to support the bucket parameter.

just to confirm, this endpoint supports the `bucket` parameter (and ignores the `db`).

I'm happy to give this ticket a go but I'd like to have a confirmation from Greptime team that it's fine to go ahead and proceed  with the proposed logic(@tisonkun  could you please help me with that?).

In my opinion the client code should decided which endpoint (`/write` or `/api/v2/write` to invoke) based on the provided query parameter (`db` for the former and `bucket` for the latter).

**Comment by nicecui** [comment] 2024-03-05 03:46
@etolbakov The `/influxdb/write` API is compatible with influxdb protocol v1 which also uses the `db` parameter, so we don't need to do anything with this API.
The `influxdb/api/v2/write` API is compatible with influxdb protocol v2, it needs to support the `db` and the `bucket` parameters as discussed above.

**Comment by tisonkun** [comment] 2024-03-05 08:52
> I'm happy to give this ticket a go but I'd like to have a confirmation from Greptime team that it's fine to go ahead and proceed with the proposed logic

Confirmed that https://github.com/GreptimeTeam/greptimedb/issues/3413#issuecomment-1975561788 is reasonable. cc @etolbakov

**Comment by tisonkun** [comment] 2024-03-05 08:53
> the client code

Maybe. But the related code snippet here is about the server side. I don't find influx client code in our repository ...

**Comment by tisonkun** [comment] 2024-03-06 02:14
Something related:

```python
p = Point("my_measurement").tag("location", "Prague").field("temperature", 25.3)
bucket = 'xxx-public'
client = InfluxDBClient(url="https://yyy.greptime.cloud/v1/influxdb/", token="username:password", org="my-org")
write_api = client.write_api(write_options=SYNCHRONOUS)
write_api.write(bucket=bucket, record=p)
```

This would fail with:

```
Reason: Unauthorized
HTTP response headers: HTTPHeaderDict({'Date': 'Wed, 06 Mar 2024 02:13:03 GMT', 'Content-Type': 'application/json', 'Content-Length': '125', 'Connection': 'keep-alive', 'x-greptime-err-code': '7005', 'x-greptime-err-msg': "Access denied for user 'uuu' to database 'greptime-public'", 'x-greptime-format': 'influxdb_v1', 'x-greptime-execution-time': '0', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Methods': 'OPTIONS', 'Access-Control-Allow-Headers': 'DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization', 'Access-Control-Max-Age': '1728000'})
HTTP response body: {"code":7005,"error":"Access denied for user 'uuu' to database 'greptime-public'","execution_time_ms":0}
```

It can be a separate issue but still relevant. I'm digging into it but post here for your information.

**Comment by tisonkun** [comment] 2024-03-06 02:34
Located. It's related to this issue and the real related code is:

https://github.com/GreptimeTeam/greptimedb/blob/5d644c0b7f38e55d45b4c46a5c2e552f25606844/src/servers/src/http/authorize.rs#L140-L154

**Comment by etolbakov** [comment] 2024-03-06 11:51
Thanks @tisonkun!
I've actually discovered that issue hard way before than found your comment 😅.  So in my `influxdb_write_v2` I pass the additional header 
```
        .header(http::header::AUTHORIZATION, "token greptime:greptime")
        .header(GREPTIME_DB_HEADER_NAME, "influxdb")
```
I'll try to come up with the PR shortly so we can have a discussion

**Comment by etolbakov** [comment] 2024-03-08 08:59
@nicecui  just to let you know the fix has been merged. Please let us know once you have a moment to test it (assume you need to wait for new release)?
Let's leave the ticket opened for now.

**Comment by nicecui** [comment] 2024-03-11 04:28
@etolbakov Thank you very much! I have tested it from the `cargo build` version and it behaves as expected. I think this issued has been solved. Also thanks to @tisonkun

**Comment by tisonkun** [comment] 2024-03-11 04:36
Closed as resolved.

Thanks for @nicecui reporting and @etolbakov fixing!

**Closed by tisonkun** 2024-03-11 04:36 UTC
Labels: Good first issue, Help wanted

**Comment by etolbakov** [comment] 2024-03-11 06:52
Great news @nicecui! I'm glad that it works!
Thanks @tisonkun for your support during my work on this issue!
