### ISSUE TITLE
High latency of InfluxDB Line Protocol 

### ISSUE THREAD

**Issue by yuanbohan** [GreptimeTeam/greptimedb#982] opened 2023-02-13 08:59 UTC
### What type of enhancement is this?

Performance

### What does the enhancement do?

The latency of writing high cardinality data into GreptimeDB via InfluxDB Line Protocol is somehow higher than expect, like at most 30s per request.

![image](https://user-images.githubusercontent.com/4557527/218414230-59197dd8-111c-401d-b6c7-3436a17f5d9a.png)

![image](https://user-images.githubusercontent.com/4557527/218414301-94d4ebea-c746-434a-bfa1-a96654134c4e.png)

**Comment by evenyag** [comment] 2023-02-14 09:48
Sounds strange 🤔 Can you reproduce this in your environment? We might need more information to diagnose this. Adding some metrics or traces to the write path is also useful.

If you don't mind, could you add some metrics or traces? We could re-export the `metrics` crate in the [common-telemetry](https://github.com/GreptimeTeam/greptimedb/blob/374acc88303bb37616880a2077b943e76f050310/src/common/telemetry/Cargo.toml#L15) crate.

**Comment by waynexia** [comment] 2023-02-16 11:41
#1023 may help

**Comment by v0y4g3r** [comment] 2023-05-09 06:42
TSBS benchmark CPU perf
![perf](https://user-images.githubusercontent.com/6406592/237015110-988364b9-24b9-436d-bb1b-60bb5e49c2d5.svg)

**Comment by evenyag** [comment] 2023-05-10 02:59
Could you reproduce this in the latest release? I ran TSBS many times and didn't see such high latency requests.

**Comment by yuanbohan** [comment] 2023-05-10 03:02
I will re-test the influxdb line protocol performance in the next days, and post the report here

**Comment by killme2008** [comment] 2023-05-10 03:46
Did it happen in a standalone version or cluster?

**Comment by yuanbohan** [comment] 2023-05-10 03:51
> Did it happen in a standalone version or cluster?

cluster

**Comment by killme2008** [comment] 2023-05-10 06:28
> > Did it happen in a standalone version or cluster?
> 
> cluster

It looks like it's expected. A lot of performance issues in the cluster version.

**Comment by killme2008** [comment] 2023-09-01 02:33
I think we can close this issue at this moment. We will do the performance benchmark again in the next release. If we still such performance issue, let's create a new issue to track it.

**Closed by killme2008** 2023-09-01 02:33 UTC
Labels: enhancement, performance
