### ISSUE TITLE
Table names not sanitized in frontend

### ISSUE THREAD

**Issue by tatticoder** [GreptimeTeam/greptimedb#1581] opened 2023-05-14 19:46 UTC
### What type of bug is this?

Unexpected error

### What subsystems are affected?

Frontend

### What happened?

I am using `NIFTY-Feb2023-17800-PE` table name and clicking on the down arrow in the side-menu to describe the table gives the following error. I am assuming it is because my table names have `-` in them as the same operation runs fine when I replace it with `_`.

![image](https://github.com/GreptimeTeam/greptimedb/assets/52121648/bb962abd-2672-4536-a83d-b102dad1a0e3)

### What operating system did you use?

Fedora 38

### How can we reproduce the bug?

Create table names with `-` in them and then click on drop-down in the sidebar. 
![image](https://github.com/GreptimeTeam/greptimedb/assets/52121648/68b41ef3-e5cd-42c5-bc35-49b2e644caac)

**Comment by killme2008** [comment] 2023-05-15 02:35
@tatticoder Thanks. Good catch! Looks like it's a bug of dashboard. 

I created an issue to track it https://github.com/GreptimeTeam/dashboard/issues/261

**Comment by NiwakaDev** [comment] 2023-05-15 03:33
@killme2008 

>Looks like it's a bug of dashboard.

By the way, I executed the following sql via the `mysql` command:

```sql
SELECT * FROM hello-world;
```

And then got the same error:

```
ERROR 1815 (HY000): Failed to execute query: SELECT * FROM hello-world, source: Failed to parse SQL, source: SQL statement is not supported: SELECT * FROM hello-world, keyword: -
```

This issue seems to be caused by `GenericDialect`.

So, I guess that the issue could be solved by introducing `GreptimeDialect`, like so:

```rust
#[derive(Debug, Default)]
pub struct GenericDialect;

impl Dialect for GreptimeDialect {
    //..
    fn is_identifier_part(&self, ch: char) -> bool {
        ch.is_alphabetic()
        //..
        || ch == '-' //Allows something like `hello-world` to be used as a table-name.
    }
}

```

What do you think about this?

**Comment by killme2008** [comment] 2023-05-15 03:36
@tatticoder 
You can use double-quoted string for table names and column names with special characters:

```
select * from "hello-world"
```

**Comment by killme2008** [comment] 2023-05-30 10:46
It's tracked in dashboard repo, so i close this issue.

**Closed by killme2008** 2023-05-30 10:46 UTC
Labels: bug
