### ISSUE TITLE
Supports SHOW FULL TABLES

### ISSUE THREAD

**Issue by killme2008** [GreptimeTeam/greptimedb#2372] opened 2023-09-13 03:25 UTC
### What type of enhancement is this?

API improvement, User experience

### What does the enhancement do?

The MySQL supports `show full tables`:

![image](https://github.com/GreptimeTeam/greptimedb/assets/14142/71a087a2-7c20-4af2-bff8-5912717128e0)

https://dev.mysql.com/doc/refman/8.0/en/show-tables.html

**Comment by mustachemo** [comment] 2023-09-13 03:37
Hello, I would like to work on this but I am a bit confused as to what the task is

**Comment by killme2008** [comment] 2023-09-13 03:42
@mustachemo If you are not familiar with MySQL or Rust, I think it's not a good first issue for you, Thank you.

**Comment by Lilit0x** [comment] 2023-09-14 23:14
Hi @killme2008 , I am interested in working on this. Below is a brief description on how I might go about it and where I will start from. Please let me know if I'm wrong or need some other resources to get me up to speed. 

- I understand that there's already a `parse_show` function after a successful match of `Keyword::SHOW` [here](https://github.com/GreptimeTeam/greptimedb/blob/d1adb915bfa18a8fe8703318d8766211e780c765/src/sql/src/parser.rs#L90) 
- Then the `parse_show` function checks the next token in which currently, `FULL` is not recognized, so it throws an error. I plan on adding another case to check if the token is `FULL`. If it is, move to the next token and also check if it matches `TABLES` then just return a `ShowTables` statement with `kind` of `FULL` (I will also add this to the enum)
- Lastly, in the `show_tables` function in the query handler [here](https://github.com/GreptimeTeam/greptimedb/blob/d1adb915bfa18a8fe8703318d8766211e780c765/src/query/src/sql.rs#L141) is where I will get the tables and get the information about each table to display in the second column. 
- I am not sure on how to get the table type yet, but I can see that the `CatalogManager` has a `table` method that returns a `Table` struct which in turn has a `table_type` method on it to get the type of the table. I mean [here](https://github.com/GreptimeTeam/greptimedb/blob/d1adb915bfa18a8fe8703318d8766211e780c765/src/table/src/table.rs#L51)
 
Thank you.

**Comment by killme2008** [comment] 2023-09-15 01:21
@Lilit0x Yes, you are right. I assigned the issue to u, thank u.

**Comment by Lilit0x** [comment] 2023-09-15 10:06
Hi @killme2008 , I face this error sometimes when I run greptime with `cargo run -- standalone start`. I can't seem to figure out what the issue is.

<img width="472" alt="greptime_err" src="https://github.com/GreptimeTeam/greptimedb/assets/52760545/c8eaef8c-5bfa-4f05-9cac-9c828ee98d70">

**Comment by killme2008** [comment] 2023-09-15 11:12
Can you delete the data in `/tmp/greptimedb`?

The new storage engine doesn't implement the recovering properly right now, it will be fixed in https://github.com/GreptimeTeam/greptimedb/pull/2399

**Comment by Lilit0x** [comment] 2023-09-15 14:08
I have deleted it and pulled the latest fix, but now it can't start the datanode because of a region issue. 
<img width="477" alt="gre_err_2" src="https://github.com/GreptimeTeam/greptimedb/assets/52760545/295e4cec-d93f-470c-a4a8-fe4480934092">

**Comment by WenyXu** [comment] 2023-09-15 14:42
@Lilit0x I submitted a quick fix in #2408 for this issue. Before it was merged, you can cherry-pick it into your branch.

**Comment by killme2008** [comment] 2023-09-16 03:39
It's fixed in https://github.com/GreptimeTeam/greptimedb/pull/2409

**Closed** 2023-09-22 02:50 UTC
Labels: enhancement, good first issue
